# Generated by Django 4.1.3 on 2022-11-07 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='Lymphocyte',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
