# Generated by Django 4.1.3 on 2022-11-08 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_sample_lymphocyte'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('sex', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient_medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='sample',
            name='User_id',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
