# Generated by Django 4.1.3 on 2022-11-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_patient_patient_medicine_sample_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='HCT',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='sample',
            name='Lymphocyte',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='sample',
            name='MCH',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='sample',
            name='MCV',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='sample',
            name='RBC',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='sample',
            name='WBC',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
