# Generated by Django 4.1.3 on 2022-11-09 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_bloodsample_result_patient_bloodsample_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_bloodsample',
            name='HealthCare_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
