# Generated by Django 4.1.3 on 2022-11-09 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_patient_bloodsample_healthcare_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient_Prescription',
        ),
        migrations.RemoveField(
            model_name='bloodsample_result',
            name='patient_id',
        ),
        migrations.RemoveField(
            model_name='patient_bloodsample',
            name='patient_id',
        ),
        migrations.AddField(
            model_name='bloodsample_result',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.patient'),
        ),
        migrations.AddField(
            model_name='patient',
            name='family_doctor',
            field=models.CharField(default='Dr. Martin', max_length=100),
        ),
        migrations.AddField(
            model_name='patient_bloodsample',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.patient'),
        ),
    ]
